# Generated by Django 4.2.6 on 2023-10-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='next_notification_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Next Notification Time'),
        ),
    ]
