# Generated by Django 4.2.6 on 2023-10-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='telegram_id',
        ),
    ]
